Pusher gem don't work with httpclient 2.5.3
Due to `'~> 2.4'` restriction you have we accidentally upgraded to 2.3.5.1 of httpclient today and it doesn't work with pusher gem.

> SocketError: getaddrinfo: Temporary failure in name resolution (https://api.pusherapp.com:443)